#!/bin/sh -e

export PREFIX=""
if [ -d 'venv' ] ; then
    export PREFIX="venv/bin/"
fi

if [ "$1" != "" ]
then
    PYTHONPATH=. ${PREFIX}pytest tests -k $1
else
    PYTHONPATH=. ${PREFIX}pytest tests --cov=belvaio_request_id --cov=tests --cov-report=term-missing:skip-covered --no-cov-on-fail
fi
